CREATE TABLE IF NOT EXISTS public.categoria
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    activa boolean,
    descripcion text COLLATE pg_catalog."default",
    eliminada boolean,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.comprobante_pago
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_subida timestamp(6) without time zone NOT NULL,
    nombre_archivo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ruta_archivo character varying(500) COLLATE pg_catalog."default" NOT NULL,
    id_pago bigint NOT NULL,
    CONSTRAINT comprobante_pago_pkey PRIMARY KEY (id),
    CONSTRAINT fkq3re245vvc1l803brhl7taig0 FOREIGN KEY (id_pago)
        REFERENCES public.pago (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.detalle_pedido
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    pedido_id bigint NOT NULL,
    variante_producto_id bigint NOT NULL,
    CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id),
    CONSTRAINT fkbvrtjiec3r7yw6ru8a5oo5cwy FOREIGN KEY (variante_producto_id)
        REFERENCES public.variante_producto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkgqvba9e7dildyw45u0usdj1k2 FOREIGN KEY (pedido_id)
        REFERENCES public.pedido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.envio
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contacto character varying(12) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_envio date,
    numero_guia character varying(100) COLLATE pg_catalog."default",
    transportista character varying(100) COLLATE pg_catalog."default",
    pedido_id bigint NOT NULL,
    usuario_empleado_id bigint,
    CONSTRAINT envio_pkey PRIMARY KEY (id),
    CONSTRAINT fka4orhwx5qfh4lgm3jovy1q6vs FOREIGN KEY (pedido_id)
        REFERENCES public.pedido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkm9er1mwbyosnp1ofkcrsctbkd FOREIGN KEY (usuario_empleado_id)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.imagen_producto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    es_principal boolean,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    orden integer,
    url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    producto_id bigint,
    variante_producto_id bigint,
    CONSTRAINT imagen_producto_pkey PRIMARY KEY (id),
    CONSTRAINT fk9k9l0b54kcvxup1v39wknhwq1 FOREIGN KEY (producto_id)
        REFERENCES public.producto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkljm24t8oo53maupjlicph7cty FOREIGN KEY (variante_producto_id)
        REFERENCES public.variante_producto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.pago
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    datos_pago jsonb,
    estado_pago character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_pago timestamp(6) without time zone,
    metodo_pago character varying(50) COLLATE pg_catalog."default" NOT NULL,
    monto numeric(10,2) NOT NULL,
    referencia_pago character varying(100) COLLATE pg_catalog."default",
    pedido_id bigint NOT NULL,
    CONSTRAINT pago_pkey PRIMARY KEY (id),
    CONSTRAINT fk8fojprqy7kv7k3d192m91e027 FOREIGN KEY (pedido_id)
        REFERENCES public.pedido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.pedido
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    costo_envio numeric(10,2),
    direccion_envio character varying(500) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    impuestos numeric(10,2),
    notas text COLLATE pg_catalog."default",
    subtotal numeric(10,2),
    telefono_contacto character varying(12) COLLATE pg_catalog."default" NOT NULL,
    total numeric(10,2),
    cliente_id bigint NOT NULL,
    CONSTRAINT pedido_pkey PRIMARY KEY (id),
    CONSTRAINT fk37ms39e5dvx6m05hftvx9uavk FOREIGN KEY (cliente_id)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.producto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    activo boolean,
    descripcion text COLLATE pg_catalog."default",
    eliminado boolean,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    imagen character varying(500) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    sku character varying(10) COLLATE pg_catalog."default",
    categoria_id bigint,
    CONSTRAINT producto_pkey PRIMARY KEY (id),
    CONSTRAINT ukclpng6f2m2r9i1y5g2yxajyuq UNIQUE (sku),
    CONSTRAINT fkodqr7965ok9rwquj1utiamt0m FOREIGN KEY (categoria_id)
        REFERENCES public.categoria (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public."reseña"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    aprobada boolean,
    calificacion integer NOT NULL,
    comentario text COLLATE pg_catalog."default",
    fecha_creacion timestamp(6) without time zone NOT NULL,
    cliente_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    CONSTRAINT "reseña_pkey" PRIMARY KEY (id),
    CONSTRAINT ukoiuwhucjq1sp922v510jgwopr UNIQUE (cliente_id, producto_id),
    CONSTRAINT fkk7gjw54j0c38j31sow5lvgd5f FOREIGN KEY (producto_id)
        REFERENCES public.producto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkqmu2nx6t0yetvlrdy0dd0yfd4 FOREIGN KEY (cliente_id)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contrasena character varying(255) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(300) COLLATE pg_catalog."default" NOT NULL,
    eliminado boolean,
    estado boolean NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_registro timestamp(6) without time zone NOT NULL,
    n_identificacion character varying(12) COLLATE pg_catalog."default" NOT NULL,
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    puntos_fidelizacion integer,
    rol character varying(20) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(12) COLLATE pg_catalog."default" NOT NULL,
    tipo_identificacion character varying(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT uk2mlfr087gb1ce55f2j87o74t UNIQUE (correo),
    CONSTRAINT uk3poocqdhcv4yw3dlykh1y7gqn UNIQUE (n_identificacion)
)

CREATE TABLE IF NOT EXISTS public.variante_producto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    activo boolean,
    precio numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    talla character varying(2) COLLATE pg_catalog."default" NOT NULL,
    producto_id bigint NOT NULL,
    CONSTRAINT variante_producto_pkey PRIMARY KEY (id),
    CONSTRAINT ukdkn5cc2fr6m68n220q2p5cvb8 UNIQUE (producto_id, talla),
    CONSTRAINT fkprkb5bek95r4mnsk44osjm7a2 FOREIGN KEY (producto_id)
        REFERENCES public.producto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

