spring.application.name=springboot_app

spring.datasource.url=jdbc:postgresql://localhost:5433/sistema_ventas_mambo
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=Jis2912
=======
spring.datasource.password=Lgian1902@
>>>>>>> c7f0a7c3c255bc5c87d2f6cfd406cbbc01c662ae

# Opcional pero útil
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log's
logging.level.com.integrador.sistema_de_ventas=DEBUG
logging.level.org.springframework.security=DEBUG

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Configuración de recursos estáticos
spring.web.resources.static-locations=classpath:/static/,classpath:/templates/

miragic.api.key=sk_live_KGgTyIM8cqDURGmbl9Fv27e9uVpcOpGGZZnaq5_mMIg
miragic.api.url=https://api.miragic.ai/vto/generate
