spring.application.name=springboot_app

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_ventas_mambo
spring.datasource.username=postgres
spring.datasource.password=E1g@t0b0b1909

# Opcional pero útil
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Log's
logging.level.com.integrador.sistema_de_ventas=DEBUG
logging.level.org.springframework.security=DEBUG

